[package]
name = "overlay"
version = "0.1.0"
authors = ["Ash Brent-Carpenter <ash@sent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svg = "0.8.0"
structopt = "0.3.17"
